import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sbiv2/data/models/models.dart';
import 'package:sbiv2/data/repositories/state_providers.dart';

class ToolDispatcher {
  static Future<Map<String, dynamic>> dispatch(Ref ref, String name, Map<String, dynamic> args) async {
    // Artificial lag to make it feel "agentic" and visible
    await Future.delayed(const Duration(milliseconds: 800));

    switch (name) {
      case 'qualify_lead':
        final incomeBracket = args['income_bracket'] ?? '0-5 Lakhs';
        final bankingNeed = args['banking_need'] ?? 'Savings & UPI';
        final existingBank = args['existing_bank'] ?? 'None';
        
        ref.read(userProfileProvider.notifier).updateQualifyData(
              incomeBracket: incomeBracket,
              bankingNeed: bankingNeed,
              existingBank: existingBank,
            );
        return {
          'status': 'qualified',
          'income_bracket': incomeBracket,
          'banking_need': bankingNeed,
          'existing_bank': existingBank,
        };

      case 'initiate_kyc_step':
        final step = args['step'] as String? ?? 'pan';
        final userConfirmed = args['user_confirmed'] as bool? ?? false;

        if (userConfirmed) {
          String nextStep = 'none';
          if (step == 'pan') {
            nextStep = 'aadhaar';
            ref.read(userProfileProvider.notifier).updateKYCStep('pan');
            ref.read(engagementProvider.notifier).addCoins(25);
          } else if (step == 'aadhaar') {
            nextStep = 'video_kyc';
            ref.read(userProfileProvider.notifier).updateKYCStep('aadhaar');
            ref.read(engagementProvider.notifier).addCoins(25);
          } else if (step == 'video_kyc') {
            nextStep = 'complete';
            ref.read(userProfileProvider.notifier).updateKYCStep('complete');
            ref.read(engagementProvider.notifier).addCoins(50);
            ref.read(engagementProvider.notifier).addAchievement('Full KYC Done');
          }
          return {
            'status': 'success',
            'step_completed': step,
            'next_step': nextStep,
            'coins_awarded': step == 'video_kyc' ? 50 : 25,
          };
        }
        return {'status': 'failed', 'reason': 'User did not confirm'};

      case 'activate_upi':
        final vpa = args['vpa'] as String? ?? 'user@sbi';
        ref.read(userProfileProvider.notifier).enableUPI(true);
        ref.read(engagementProvider.notifier).addCoins(30);
        ref.read(engagementProvider.notifier).addAchievement('UPI Enabled');
        return {
          'status': 'success',
          'upi_id': vpa,
          'coins_awarded': 30,
        };

      case 'surface_recommendation':
        final recId = args['recommendation_id'] as String? ?? 'rec_custom';
        final reason = args['reason'] as String? ?? 'AI suggested standard action';

        final rec = Recommendation(
          id: recId,
          title: recId == 'rec_fd' ? 'Open SBI Tax Saver FD' : 'SBI SIP Builder',
          subtitle: recId == 'rec_fd' ? 'Lock in 7.2% secure returns' : 'Grow wealth with auto SIPs',
          aiReason: reason,
          priority: 0,
          isCompleted: false,
        );

        ref.read(recommendationsProvider.notifier).addRecommendation(rec);
        return {
          'status': 'success',
          'recommendation_id': recId,
        };

      case 'log_spending_insight':
        final category = args['category'] as String? ?? 'General';
        final observation = args['observation'] as String? ?? 'Spending detected';
        final reason = args['reason'] as String? ?? 'Anomaly trigger';

        // Add transaction alert or recommendation
        final rec = Recommendation(
          id: 'insight_${DateTime.now().millisecondsSinceEpoch}',
          title: 'Alert: $observation',
          subtitle: 'Category: $category. $reason',
          aiReason: 'Automatic Spending Insight generated by AI Pattern Engine.',
          priority: 2,
          isCompleted: false,
        );
        ref.read(recommendationsProvider.notifier).addRecommendation(rec);
        return {
          'status': 'success',
          'insight_category': category,
        };

      case 'boost_goal_savings':
        final goalId = args['goal_id'] as String? ?? 'goal_01';
        final amount = (args['amount'] as num? ?? 100).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to boost goal'};
        }

        // Deduct from profile balance
        ref.read(userProfileProvider.notifier).updateBalance(-amount);

        // Add to goal savings
        ref.read(goalsProvider.notifier).boostGoal(goalId, amount);

        // Log transaction
        final newTx = Transaction(
          id: 'tx_boost_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: 'Goal Boost: $goalId',
          category: 'Investment',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);
        ref.read(engagementProvider.notifier).addCoins(10);

        return {
          'status': 'success',
          'goal_id': goalId,
          'amount_boosted': amount,
          'coins_awarded': 10,
        };

      case 'execute_transfer':
        final recipient = args['recipient'] as String? ?? 'Self';
        final amount = (args['amount'] as num? ?? 0).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to execute transfer'};
        }

        // Deduct from profile balance
        ref.read(userProfileProvider.notifier).updateBalance(-amount);

        // Create transaction
        final newTx = Transaction(
          id: 'tx_transfer_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: recipient,
          category: 'Transfer',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);

        return {
          'status': 'success',
          'recipient': recipient,
          'amount_transferred': amount,
        };

      case 'suggest_service_activation':
        final serviceId = args['service_id'] as String? ?? 'srv_sip';

        ref.read(servicesProvider.notifier).activateService(serviceId);
        ref.read(engagementProvider.notifier).addCoins(50);
        ref.read(engagementProvider.notifier).addAchievement('Service Activated: $serviceId');
        return {
          'status': 'success',
          'service_id': serviceId,
          'coins_awarded': 50,
        };

      default:
        return {'status': 'error', 'reason': 'Unknown tool name: $name'};
    }
  }
}
