import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sbiv2/data/models/models.dart';
import 'package:sbiv2/data/repositories/state_providers.dart';
import 'package:sbiv2/ai/memory/agent_memory.dart';

class ToolDispatcher {
  static Future<Map<String, dynamic>> dispatch(Ref ref, String name, Map<String, dynamic> args) async {
    // Artificial lag to make it feel "agentic" and visible
    await Future.delayed(const Duration(milliseconds: 800));

    // Update agent memory with the last executed tool
    ref.read(agentMemoryProvider.notifier).logToolExecution(name);

    switch (name) {
      case 'qualify_lead':
        final incomeBracket = args['income_bracket'] ?? '0-5 Lakhs';
        final bankingNeed = args['banking_need'] ?? 'Savings & UPI';
        final existingBank = args['existing_bank'] ?? 'None';
        
        ref.read(userProfileProvider.notifier).updateQualifyData(
              incomeBracket: incomeBracket,
              bankingNeed: bankingNeed,
              existingBank: existingBank,
            );
        return {
          'status': 'qualified',
          'income_bracket': incomeBracket,
          'banking_need': bankingNeed,
          'existing_bank': existingBank,
        };

      case 'start_kyc':
      case 'initiate_kyc_step':
        final step = args['step'] as String? ?? 'pan';
        final userConfirmed = args['user_confirmed'] as bool? ?? false;

        if (userConfirmed) {
          String nextStep = 'none';
          if (step == 'pan') {
            nextStep = 'aadhaar';
            ref.read(userProfileProvider.notifier).updateKYCStep('pan');
            ref.read(engagementProvider.notifier).addCoins(25);
            ref.read(agentMemoryProvider.notifier).updateKYCStep('pan');
          } else if (step == 'aadhaar') {
            nextStep = 'video_kyc';
            ref.read(userProfileProvider.notifier).updateKYCStep('aadhaar');
            ref.read(engagementProvider.notifier).addCoins(25);
            ref.read(agentMemoryProvider.notifier).updateKYCStep('aadhaar');
          } else if (step == 'video_kyc') {
            nextStep = 'complete';
            ref.read(userProfileProvider.notifier).updateKYCStep('complete');
            ref.read(engagementProvider.notifier).addCoins(50);
            ref.read(engagementProvider.notifier).addAchievement('Full KYC Done');
            ref.read(agentMemoryProvider.notifier).updateKYCStep('complete');
          }
          return {
            'status': 'success',
            'step_completed': step,
            'next_step': nextStep,
            'coins_awarded': step == 'video_kyc' ? 50 : 25,
          };
        }
        return {'status': 'failed', 'reason': 'User did not confirm'};

      case 'activate_upi':
        final vpa = args['vpa'] as String? ?? 'user@sbi';
        ref.read(userProfileProvider.notifier).enableUPI(true);
        ref.read(engagementProvider.notifier).addCoins(30);
        ref.read(engagementProvider.notifier).addAchievement('UPI Enabled');
        ref.read(agentMemoryProvider.notifier).updateKYCStep('complete');
        return {
          'status': 'success',
          'upi_id': vpa,
          'coins_awarded': 30,
        };

      case 'surface_recommendation':
        final recId = args['recommendation_id'] as String? ?? 'rec_custom';
        final reason = args['reason'] as String? ?? 'AI suggested standard action';

        final rec = Recommendation(
          id: recId,
          title: recId == 'rec_fd' ? 'Open SBI Tax Saver FD' : 'SBI SIP Builder',
          subtitle: recId == 'rec_fd' ? 'Lock in 7.2% secure returns' : 'Grow wealth with auto SIPs',
          aiReason: reason,
          priority: 0,
          isCompleted: false,
        );

        ref.read(recommendationsProvider.notifier).addRecommendation(rec);
        return {
          'status': 'success',
          'recommendation_id': recId,
        };

      case 'log_insight':
      case 'log_spending_insight':
        final category = args['category'] as String? ?? 'General';
        final observation = args['observation'] as String? ?? 'Spending detected';
        final reason = args['reason'] as String? ?? 'Anomaly trigger';

        final rec = Recommendation(
          id: 'insight_${DateTime.now().millisecondsSinceEpoch}',
          title: 'Alert: $observation',
          subtitle: 'Category: $category. $reason',
          aiReason: 'Automatic Spending Insight generated by AI Pattern Engine.',
          priority: 2,
          isCompleted: false,
        );
        ref.read(recommendationsProvider.notifier).addRecommendation(rec);
        return {
          'status': 'success',
          'insight_category': category,
        };

      case 'boost_goal_savings':
        final goalId = args['goal_id'] as String? ?? 'goal_01';
        final amount = (args['amount'] as num? ?? 100).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to boost goal'};
        }

        ref.read(userProfileProvider.notifier).updateBalance(-amount);
        ref.read(goalsProvider.notifier).boostGoal(goalId, amount);

        final newTx = Transaction(
          id: 'tx_boost_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: 'Goal Boost: $goalId',
          category: 'Investment',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);
        ref.read(engagementProvider.notifier).addCoins(10);

        return {
          'status': 'success',
          'goal_id': goalId,
          'amount_boosted': amount,
          'coins_awarded': 10,
        };

      case 'transfer_money':
      case 'execute_transfer':
        final recipient = args['recipient'] as String? ?? 'Self';
        final amount = (args['amount'] as num? ?? 0).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to execute transfer'};
        }

        ref.read(userProfileProvider.notifier).updateBalance(-amount);

        final newTx = Transaction(
          id: 'tx_transfer_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: recipient,
          category: 'Transfer',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);

        return {
          'status': 'success',
          'recipient': recipient,
          'amount_transferred': amount,
        };

      case 'move_to_fd':
        final amount = (args['amount'] as num? ?? 50000.0).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to open Fixed Deposit'};
        }

        ref.read(userProfileProvider.notifier).updateBalance(-amount);
        ref.read(servicesProvider.notifier).activateService('srv_fd');
        ref.read(engagementProvider.notifier).addCoins(50);
        ref.read(engagementProvider.notifier).addAchievement('Fixed Deposit Opened');

        final newTx = Transaction(
          id: 'tx_fd_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: 'SBI Fixed Deposit',
          category: 'Investment',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);

        return {
          'status': 'success',
          'service_id': 'srv_fd',
          'amount_locked': amount,
          'coins_awarded': 50,
        };

      case 'resume_sip':
        final profile = ref.read(userProfileProvider);
        const amount = 5000.0;
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient balance to resume SIP'};
        }

        ref.read(userProfileProvider.notifier).updateBalance(-amount);
        ref.read(servicesProvider.notifier).activateService('srv_sip');
        ref.read(engagementProvider.notifier).addCoins(50);
        ref.read(engagementProvider.notifier).addAchievement('SIP Resumed');

        final newTx = Transaction(
          id: 'tx_sip_${DateTime.now().millisecondsSinceEpoch}',
          amount: amount,
          payee: 'SBI Bluechip Fund (SIP)',
          category: 'Investment',
          date: DateTime.now(),
          type: 'debit',
        );
        ref.read(transactionsProvider.notifier).addTransaction(newTx);
        ref.read(agentMemoryProvider.notifier).updateSIPDate(DateTime.now().toIso8601String());

        return {
          'status': 'success',
          'service_id': 'srv_sip',
          'amount_debited': amount,
          'coins_awarded': 50,
        };

      case 'create_goal':
        final name = args['name'] as String? ?? 'Custom Goal';
        final targetAmount = (args['target_amount'] as num? ?? 10000.0).toDouble();

        final goalId = 'goal_${DateTime.now().millisecondsSinceEpoch}';
        final goal = Goal(
          id: goalId,
          name: name,
          targetAmount: targetAmount,
          savedAmount: 0.0,
          deadline: DateTime.now().add(const Duration(days: 180)),
        );

        ref.read(goalsProvider.notifier).addGoal(goal);
        return {
          'status': 'success',
          'goal_id': goalId,
          'goal_name': name,
          'target_amount': targetAmount,
        };

      case 'suggest_service_activation':
        final serviceId = args['service_id'] as String? ?? 'srv_sip';

        ref.read(servicesProvider.notifier).activateService(serviceId);
        ref.read(engagementProvider.notifier).addCoins(50);
        ref.read(engagementProvider.notifier).addAchievement('Service Activated: $serviceId');
        return {
          'status': 'success',
          'service_id': serviceId,
          'coins_awarded': 50,
        };

      case 'manage_sip':
        final action = args['action'] as String? ?? 'create';
        final fundName = args['fund_name'] as String? ?? 'SBI Bluechip Fund';
        final amount = (args['amount'] as num? ?? 5000.0).toDouble();

        if (action == 'create') {
          final profile = ref.read(userProfileProvider);
          if (profile.balance < amount) {
            return {'status': 'failed', 'reason': 'Insufficient balance to start SIP'};
          }
          ref.read(userProfileProvider.notifier).updateBalance(-amount);
          ref.read(sipListProvider.notifier).createSIP(fundName, amount, category: fundName.contains('Small') ? 'Small Cap' : 'Large Cap');
          ref.read(servicesProvider.notifier).activateService('srv_sip');
          
          final newTx = Transaction(
            id: 'tx_sip_${DateTime.now().millisecondsSinceEpoch}',
            amount: amount,
            payee: '$fundName (SIP)',
            category: 'Investment',
            date: DateTime.now(),
            type: 'debit',
          );
          ref.read(transactionsProvider.notifier).addTransaction(newTx);
          ref.read(engagementProvider.notifier).addCoins(50);
          return {'status': 'success', 'message': 'SIP of ₹${amount.toStringAsFixed(0)} registered in $fundName.'};
        } else if (action == 'update') {
          final sips = ref.read(sipListProvider);
          final match = sips.firstWhere((s) => s.fundName.toLowerCase().contains(fundName.toLowerCase()) && s.status == 'active', 
              orElse: () => sips.firstWhere((s) => s.status == 'active', 
                  orElse: () => SipInvestment(id: '', fundName: '', amount: 0, nextPaymentDate: '', category: '', status: '')));
          if (match.id.isEmpty) {
            return {'status': 'failed', 'reason': 'No active SIP found to update'};
          }
          ref.read(sipListProvider.notifier).updateSIP(match.id, amount);
          return {'status': 'success', 'message': 'SIP for ${match.fundName} updated to ₹${amount.toStringAsFixed(0)}.'};
        } else if (action == 'cancel') {
          final sips = ref.read(sipListProvider);
          final match = sips.firstWhere((s) => s.fundName.toLowerCase().contains(fundName.toLowerCase()) && s.status == 'active', 
              orElse: () => sips.firstWhere((s) => s.status == 'active', 
                  orElse: () => SipInvestment(id: '', fundName: '', amount: 0, nextPaymentDate: '', category: '', status: '')));
          if (match.id.isEmpty) {
            return {'status': 'failed', 'reason': 'No active SIP found to cancel'};
          }
          ref.read(sipListProvider.notifier).cancelSIP(match.id);
          return {'status': 'success', 'message': 'SIP for ${match.fundName} has been cancelled.'};
        }
        return {'status': 'failed', 'reason': 'Invalid action: $action'};

      case 'manage_fd':
        final action = args['action'] as String? ?? 'open';
        final title = args['title'] as String? ?? 'Standard FD';
        final amount = (args['amount'] as num? ?? 50000.0).toDouble();
        final autoRenew = args['auto_renew'] as bool? ?? false;

        if (action == 'open') {
          final profile = ref.read(userProfileProvider);
          if (profile.balance < amount) {
            return {'status': 'failed', 'reason': 'Insufficient balance to open Fixed Deposit'};
          }
          ref.read(userProfileProvider.notifier).updateBalance(-amount);
          ref.read(fdListProvider.notifier).openFD(title, amount, autoRenew: autoRenew);
          ref.read(servicesProvider.notifier).activateService('srv_fd');
          ref.read(engagementProvider.notifier).addCoins(50);

          final newTx = Transaction(
            id: 'tx_fd_${DateTime.now().millisecondsSinceEpoch}',
            amount: amount,
            payee: 'SBI Fixed Deposit ($title)',
            category: 'Investment',
            date: DateTime.now(),
            type: 'debit',
          );
          ref.read(transactionsProvider.notifier).addTransaction(newTx);
          return {'status': 'success', 'message': 'Fixed Deposit of ₹${amount.toStringAsFixed(0)} opened successfully.'};
        } else if (action == 'close') {
          final fds = ref.read(fdListProvider);
          final match = fds.firstWhere((fd) => fd.title.toLowerCase().contains(title.toLowerCase()),
              orElse: () => fds.isNotEmpty ? fds.first : FixedDeposit(id: '', title: '', principalAmount: 0, interestRate: 0, maturityDate: DateTime.now(), isAutoRenew: false));
          if (match.id.isEmpty) {
            return {'status': 'failed', 'reason': 'No active FD found to close'};
          }
          ref.read(userProfileProvider.notifier).updateBalance(match.principalAmount);
          ref.read(fdListProvider.notifier).closeFD(match.id);
          
          final newTx = Transaction(
            id: 'tx_fd_close_${DateTime.now().millisecondsSinceEpoch}',
            amount: match.principalAmount,
            payee: 'FD Closure Credit: ${match.title}',
            category: 'Investment',
            date: DateTime.now(),
            type: 'credit',
          );
          ref.read(transactionsProvider.notifier).addTransaction(newTx);
          return {'status': 'success', 'message': 'Fixed Deposit "${match.title}" closed prematurely. ₹${match.principalAmount.toStringAsFixed(0)} credited back.'};
        } else if (action == 'renew') {
          final fds = ref.read(fdListProvider);
          final match = fds.firstWhere((fd) => fd.title.toLowerCase().contains(title.toLowerCase()),
              orElse: () => fds.isNotEmpty ? fds.first : FixedDeposit(id: '', title: '', principalAmount: 0, interestRate: 0, maturityDate: DateTime.now(), isAutoRenew: false));
          if (match.id.isEmpty) {
            return {'status': 'failed', 'reason': 'No active FD found to renew'};
          }
          ref.read(fdListProvider.notifier).toggleAutoRenew(match.id);
          return {'status': 'success', 'message': 'Fixed Deposit auto-renewal status updated.'};
        }
        return {'status': 'failed', 'reason': 'Invalid action: $action'};

      case 'manage_loan':
        final action = args['action'] as String? ?? 'pay_emi';
        final loanId = args['loan_id'] as String? ?? 'loan_01';
        final amount = (args['amount'] as num? ?? 28500.0).toDouble();

        final profile = ref.read(userProfileProvider);
        if (profile.balance < amount) {
          return {'status': 'failed', 'reason': 'Insufficient account balance for loan action.'};
        }

        final loans = ref.read(loanListProvider);
        final match = loans.firstWhere((l) => l.id == loanId, 
            orElse: () => loans.isNotEmpty ? loans.first : Loan(id: '', title: '', accountNumber: '', outstandingBalance: 0, emiAmount: 0, nextDueDate: '', percentRepaid: 0));
        if (match.id.isEmpty) {
          return {'status': 'failed', 'reason': 'No active loan found.'};
        }

        ref.read(userProfileProvider.notifier).updateBalance(-amount);

        if (action == 'pay_emi') {
          ref.read(loanListProvider.notifier).payEMI(match.id, amount);
          final newTx = Transaction(
            id: 'tx_loan_emi_${DateTime.now().millisecondsSinceEpoch}',
            amount: amount,
            payee: 'SBI Loan EMI Payment',
            category: 'Bills',
            date: DateTime.now(),
            type: 'debit',
          );
          ref.read(transactionsProvider.notifier).addTransaction(newTx);
          return {'status': 'success', 'message': 'EMI of ₹${amount.toStringAsFixed(0)} successfully paid for loan: ${match.title}.'};
        } else if (action == 'prepay') {
          ref.read(loanListProvider.notifier).prepayLoan(match.id, amount);
          final newTx = Transaction(
            id: 'tx_loan_prepay_${DateTime.now().millisecondsSinceEpoch}',
            amount: amount,
            payee: 'SBI Loan Prepayment',
            category: 'Investment',
            date: DateTime.now(),
            type: 'debit',
          );
          ref.read(transactionsProvider.notifier).addTransaction(newTx);
          return {'status': 'success', 'message': 'Prepayment of ₹${amount.toStringAsFixed(0)} paid towards loan: ${match.title}.'};
        }
        return {'status': 'failed', 'reason': 'Invalid action: $action'};

      case 'manage_budget':
        final action = args['action'] as String? ?? 'set_limit';
        final limit = (args['limit'] as num? ?? 45000.0).toDouble();
        final category = args['category'] as String? ?? 'Others';

        if (action == 'set_limit') {
          ref.read(budgetProvider.notifier).setBudgetLimit(limit);
          return {'status': 'success', 'message': 'Monthly budget limit updated to ₹${limit.toStringAsFixed(0)}.'};
        } else if (action == 'set_category_limit') {
          ref.read(budgetProvider.notifier).setCategoryLimit(category, limit);
          return {'status': 'success', 'message': 'Budget limit for category "$category" updated to ₹${limit.toStringAsFixed(0)}.'};
        }
        return {'status': 'failed', 'reason': 'Invalid action: $action'};

      default:
        return {'status': 'error', 'reason': 'Unknown tool name: $name'};
    }
  }
}
